version: '3'
services:
  flask_app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
        MONGO_HOST: database
        MONGO_PORT: 27017
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    
  database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - dbdata:/data/db
  
  proxy_server:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - flask_app
  
volumes:
  dbdata:
