version: '3.9'
services:
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
  web1:
    build: ./backend
    ports:
      - 81:5000
    depends_on:
      - redis
  web2:
    build: ./backend
    ports:
      - 82:5000
    depends_on:
      - redis
  proxy_server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2

    